export const movieNames = [
  "12 Angry Men",
  "1917",
  "2001: A Space Odyssey",
  "3 Idiots",
  "12 Years a Slave",
  "A Beautiful Mind",
  "A Clockwork Orange",
  "A Man Called Otto",
  "A Quiet Place",
  "A Separation",
  "A Star Is Born",
  "Adipurush",
  "Aftersun",
  "Aladdin",
  "Ala Vaikunthapurramuloo",
  "Alien",
  "All About Eve",
  "All Quiet on the Western Front",
  "Amadeus",
  "Amélie",
  "American Beauty",
  "American History X",
  "Amores Perros",
  "Anatomy of a Fall",
  "Andhadhun",
  "Animal",
  "Annie Hall",
  "Another Round",
  "Ant-Man and the Wasp: Quantumania",
  "Apocalypse Now",
  "Aquaman and the Lost Kingdom",
  "Argo",
  "Argylle",
  "Arjun Reddy",
  "Arrival",
  "Article 15",
  "Asuran",
  "Avatar",
  "Avatar: The Way of Water",
  "Baahubali: The Beginning",
  "Baahubali 2: The Conclusion",
  "Babylon",
  "Back to the Future",
  "Badhaai Ho",
  "Bangalore Days",
  "Barbie",
  "Barfi!",
  "Batman Begins",
  "Beauty and the Beast",
  "Before Sunrise",
  "Belfast",
  "Bhaag Milkha Bhaag",
  "Bicycle Thieves",
  "Birdman",
  "Black Panther",
  "Black Panther: Wakanda Forever",
  "Blade Runner",
  "Blade Runner 2049",
  "Bob Marley: One Love",
  "Bohemian Rhapsody",
  "Brahmāstra: Part One – Shiva",
  "Braveheart",
  "Breakfast at Tiffany's",
  "Broker",
  "Brokeback Mountain",
  "Bullet Train",
  "Casablanca",
  "Catch Me If You Can",
  "Chinatown",
  "Cidade de Deus",
  "Cinema Paradiso",
  "Citizen Kane",
  "City Lights",
  "Close",
  "Coco",
  "Compartment No. 6",
  "Cool Hand Luke",
  "Creed III",
  "Crouching Tiger, Hidden Dragon",
  "Dances with Wolves",
  "Dangal",
  "Das Boot",
  "Dead Poets Society",
  "Death on the Nile",
  "Decision to Leave",
  "Deadpool 3",
  "Dil Chahta Hai",
  "Dilwale Dulhania Le Jayenge",
  "Django Unchained",
  "Doctor Zhivago",
  "Don't Worry Darling",
  "Donnie Darko",
  "Double Indemnity",
  "Dr. Strangelove",
  "Drive",
  "Drive My Car",
  "Drishyam",
  "Drishyam 2",
  "Dunki",
  "Dunkirk",
  "Dune",
  "Dune: Part Two",
  "E.T. the Extra-Terrestrial",
  "Edge of Tomorrow",
  "El Laberinto del Fauno",
  "Elvis",
  "Enola Holmes 2",
  "EO",
  "Eternal Sunshine of the Spotless Mind",
  "Everything Everywhere All At Once",
  "Ex Machina",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "Fargo",
  "Fight Club",
  "Fighter",
  "Finding Nemo",
  "Five Nights at Freddy's",
  "Forrest Gump",
  "Full Metal Jacket",
  "Furiosa: A Mad Max Saga",
  "Gangubai Kathiawadi",
  "Gangs of Wasseypur",
  "Gattaca",
  "Gladiator",
  "Gladiator 2",
  "Glass Onion: A Knives Out Mystery",
  "Gone Girl",
  "Gone with the Wind",
  "Good Will Hunting",
  "Goodfellas",
  "Gran Torino",
  "Grave of the Fireflies",
  "Gravity",
  "Grease",
  "Groundhog Day",
  "Guardians of the Galaxy Vol. 3",
  "Guillermo del Toro's Pinocchio",
  "Gully Boy",
  "Hamilton",
  "Harry Potter and the Sorcerer's Stone",
  "Her",
  "Hidden Figures",
  "Holy Spider",
  "Hugo",
  "In Bruges",
  "In the Mood for Love",
  "Inception",
  "Indiana Jones",
  "Indiana Jones and the Dial of Destiny",
  "Inglourious Basterds",
  "Inside Out",
  "Interstellar",
  "Jawan",
  "Jaws",
  "John Wick: Chapter 4",
  "Joker",
  "Joker: Folie à Deux",
  "Judas and the Black Messiah",
  "Jurassic Park",
  "Jurassic World Dominion",
  "Kabhi Khushi Kabhie Gham",
  "Kantara",
  "KGF: Chapter 1",
  "KGF: Chapter 2",
  "KGF: Chapter 3",
  "Kill Bill: Vol. 1",
  "Killers of the Flower Moon",
  "Kingdom of the Planet of the Apes",
  "Knives Out",
  "Kumbalangi Nights",
  "Kung Fu Panda 4",
  "La La Land",
  "La Vita è Bella",
  "Lagaan",
  "Lady Bird",
  "Léon: The Professional",
  "Les Misérables",
  "Let the Right One In",
  "Licorice Pizza",
  "Life Is Beautiful",
  "Life of Pi",
  "Lightyear",
  "Little Women",
  "Lock, Stock and Two Smoking Barrels",
  "Logan",
  "Lost in Translation",
  "Lucifer",
  "M3GAN",
  "Mad Max: Fury Road",
  "Magnolia",
  "Mamma Mia!",
  "Manchester by the Sea",
  "March of the Penguins",
  "Marriage Story",
  "Masaan",
  "Matrix",
  "Mean Girls: The Musical",
  "Memento",
  "Memories of Murder",
  "Metropolis",
  "Midnight in Paris",
  "Minari",
  "Mission: Impossible",
  "Mission: Impossible - Dead Reckoning Part One",
  "Modern Times",
  "Monsters, Inc.",
  "Moonlight",
  "Mother India",
  "Moulin Rouge!",
  "Mr. Smith Goes to Washington",
  "Mufasa: The Lion King",
  "Mughal-e-Azam",
  "Mulholland Drive",
  "My Neighbor Totoro",
  "Napoleon",
  "Nausicaä of the Valley of the Wind",
  "Newton",
  "Nightmare Alley",
  "No Country for Old Men",
  "No Time to Die",
  "Nomadland",
  "Nope",
  "North by Northwest",
  "Notting Hill",
  "Oldboy",
  "OMG 2",
  "On the Waterfront",
  "Once Upon a Time in America",
  "Once Upon a Time in Hollywood",
  "Once Upon a Time in the West",
  "One Flew Over the Cuckoo's Nest",
  "Oppenheimer",
  "Paan Singh Tomar",
  "Padmaavat",
  "Pan's Labyrinth",
  "Parasite",
  "Past Lives",
  "Paterson",
  "Pathaan",
  "Paths of Glory",
  "Pather Panchali",
  "Pearl",
  "Perfect Days",
  "Petite Maman",
  "Pirates of the Caribbean",
  "PK",
  "Platoon",
  "Ponniyin Selvan",
  "Portrait of a Lady on Fire",
  "Premam",
  "Prey",
  "Prisoners",
  "Promising Young Woman",
  "Psycho",
  "Pulp Fiction",
  "Puss in Boots: The Last Wish",
  "Pushpa: The Rise",
  "Pushpa 2: The Rule",
  "Queen",
  "Quo Vadis, Aida?",
  "Raging Bull",
  "Raiders of the Lost Ark",
  "Rain Man",
  "Ratatouille",
  "Rear Window",
  "Requiem for a Dream",
  "Reservoir Dogs",
  "Return to Seoul",
  "Rocky",
  "Rocky Aur Rani Kii Prem Kahaani",
  "Roma",
  "Roman Holiday",
  "RRR",
  "Salaar",
  "Sam Bahadur",
  "Saving Private Ryan",
  "Scarface",
  "Schindler's List",
  "Se7en",
  "Seven Samurai",
  "Shakespeare in Love",
  "Shawshank Redemption",
  "Sherlock Holmes",
  "Shershaah",
  "Sholay",
  "Shrek",
  "Shubh Mangal Zyada Saavdhan",
  "Silence of the Lambs",
  "Silver Linings Playbook",
  "Sin City",
  "Singin' in the Rain",
  "Sita Ramam",
  "Slumdog Millionaire",
  "Smile",
  "Snatch",
  "Snow White",
  "Social Network",
  "Some Like It Hot",
  "Sonic the Hedgehog 2",
  "Soul",
  "Sound of Metal",
  "Spider-Man: Across the Spider-Verse",
  "Spider-Man: Into the Spider-Verse",
  "Spirited Away",
  "Spotlight",
  "Spring, Summer, Fall, Winter... and Spring",
  "Stalker",
  "Star Trek",
  "Star Wars: Episode IV - A New Hope",
  "Stardust",
  "Stree",
  "Stranger Than Fiction",
  "Sunset Boulevard",
  "Super Deluxe",
  "Superbad",
  "Swades",
  "Taare Zameen Par",
  "Taxi Driver",
  "Tenet",
  "Terminator 2: Judgment Day",
  "Thappad",
  "The Adam Project",
  "The Apartment",
  "The Artist",
  "The Avengers",
  "The Avengers: Endgame",
  "The Banshees of Inisherin",
  "The Batman",
  "The Big Lebowski",
  "The Big Short",
  "The Bourne Identity",
  "The Breakfast Club",
  "The Bridge on the River Kwai",
  "The Color Purple",
  "The Curious Case of Benjamin Button",
  "The Dark Knight",
  "The Dark Knight Rises",
  "The Deer Hunter",
  "The Departed",
  "The Devil Wears Prada",
  "The Eight Mountains",
  "The Elephant Man",
  "The Exorcist",
  "The Fabelmans",
  "The Farewell",
  "The Father",
  "The Flash",
  "The Florida Project",
  "The French Dispatch",
  "The Godfather",
  "The Godfather: Part II",
  "The Goonies",
  "The Grand Budapest Hotel",
  "The Green Mile",
  "The Handmaiden",
  "The Hangover",
  "The Help",
  "The Hobbit",
  "The Hunger Games",
  "The Hunger Games: The Ballad of Songbirds & Snakes",
  "The Hunt",
  "The Hurt Locker",
  "The Imitation Game",
  "The Incredibles",
  "The Intouchables",
  "The Irishman",
  "The Kerala Story",
  "The King's Speech",
  "The Lighthouse",
  "The Lion King",
  "The Little Mermaid",
  "The Lives of Others",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lost City",
  "The Lunchbox",
  "The Machinist",
  "The Maltese Falcon",
  "The Martian",
  "The Master",
  "The Menu",
  "The Northman",
  "The Notebook",
  "The Parent Trap",
  "The Pianist",
  "The Power of the Dog",
  "The Prestige",
  "The Princess Bride",
  "The Quiet Girl",
  "The Revenant",
  "The Salesman",
  "The Secret in Their Eyes",
  "The Shape of Water",
  "The Shining",
  "The Silence",
  "The Social Dilemma",
  "The Sound of Music",
  "The Super Mario Bros. Movie",
  "The Terminator",
  "The Thing",
  "The Third Man",
  "The Trial of the Chicago 7",
  "The Truman Show",
  "The Usual Suspects",
  "The Wailing",
  "The Whale",
  "The Wizard of Oz",
  "The Wolf of Wall Street",
  "The Woman King",
  "The Worst Person in the World",
  "The Zone of Interest",
  "There Will Be Blood",
  "Three Billboards Outside Ebbing, Missouri",
  "Tiger 3",
  "Titane",
  "Titanic",
  "To Kill a Mockingbird",
  "Tokyo Story",
  "Top Gun",
  "Top Gun: Maverick",
  "Toy Story",
  "Train to Busan",
  "Trainspotting",
  "Triangle of Sadness",
  "Troy",
  "Tu Jhoothi Main Makkaar",
  "Tumbbad",
  "Twelve Monkeys",
  "Uncharted",
  "Uncut Gems",
  "Up",
  "Uri: The Surgical Strike",
  "Vertigo",
  "Vikram",
  "Vikram Vedha",
  "WALL-E",
  "Where the Crawdads Sing",
  "Whiplash",
  "Wicked Part 1",
  "Wild Strawberries",
  "Willy Wonka & the Chocolate Factory",
  "Witness for the Prosecution",
  "Women Talking",
  "Wonder Woman",
  "Wonka",
  "X",
  "Y Tu Mamá También",
  "Yeh Jawaani Hai Deewani",
  "Zindagi Na Milegi Dobara",
  "Zodiac",
  "Zootopia",
];
